/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as BestsellersRouteImport } from './routes/bestsellers'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as BookSlugRouteImport } from './routes/book.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const BestsellersRoute = BestsellersRouteImport.update({
  id: '/bestsellers',
  path: '/bestsellers',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRoute
  '/bestsellers': typeof BestsellersRoute
  '/books': typeof BooksRoute
  '/categories': typeof CategoriesRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/wishlist': typeof WishlistRoute
  '/book/$slug': typeof BookSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRoute
  '/bestsellers': typeof BestsellersRoute
  '/books': typeof BooksRoute
  '/categories': typeof CategoriesRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/wishlist': typeof WishlistRoute
  '/book/$slug': typeof BookSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRoute
  '/bestsellers': typeof BestsellersRoute
  '/books': typeof BooksRoute
  '/categories': typeof CategoriesRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/wishlist': typeof WishlistRoute
  '/book/$slug': typeof BookSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/authors'
    | '/bestsellers'
    | '/books'
    | '/categories'
    | '/new-arrivals'
    | '/wishlist'
    | '/book/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/authors'
    | '/bestsellers'
    | '/books'
    | '/categories'
    | '/new-arrivals'
    | '/wishlist'
    | '/book/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/authors'
    | '/bestsellers'
    | '/books'
    | '/categories'
    | '/new-arrivals'
    | '/wishlist'
    | '/book/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthorsRoute: typeof AuthorsRoute
  BestsellersRoute: typeof BestsellersRoute
  BooksRoute: typeof BooksRoute
  CategoriesRoute: typeof CategoriesRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  WishlistRoute: typeof WishlistRoute
  BookSlugRoute: typeof BookSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestsellers': {
      id: '/bestsellers'
      path: '/bestsellers'
      fullPath: '/bestsellers'
      preLoaderRoute: typeof BestsellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthorsRoute: AuthorsRoute,
  BestsellersRoute: BestsellersRoute,
  BooksRoute: BooksRoute,
  CategoriesRoute: CategoriesRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  WishlistRoute: WishlistRoute,
  BookSlugRoute: BookSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
